version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: carrental-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 15713007
      MYSQL_DATABASE: carrental
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p15713007"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./carrental-backend
      dockerfile: Dockerfile
    container_name: carrental-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/carrental
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 15713007
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./carrental-frontend
      dockerfile: Dockerfile
    container_name: carrental-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8081
    depends_on:
      - backend

volumes:
  mysql-data: